### ISSUE TITLE
Swift check JSON send to JSONUtils.dictionify has a valid format

### ISSUE THREAD

**Issue by fnva** [AdaptiveMe/adaptive-arp-darwin#66]
see https://github.com/AdaptiveMe/adaptive-arp-darwin/blob/master/adaptive-arp-rt/Source/Sources.Api/ContactBridge.swift (line 336)

**Comment by carloslozano** [comment]
To check objects and arrays for formating.

**Comment by carloslozano** [comment]
Fixed. Callback tests OK. Listeners are the same.
