### ISSUE TITLE
invoke Method. ERROR When returning Array of Enums

### ISSUE THREAD

**Issue by fnva** [AdaptiveMe/adaptive-arp-darwin#84]
The JSON generated for the method getOrientationsSupported is:
```json
{ "response": "{[ \"value\": \"Portrait_Up\", \"value\": \"Portrait_Down\", \"value\": \"Landscape_Left\", \"value\": \"Landscape_Right\" ]}", "statusCode": 200, "statusMessage": "OK" }
```
This JSON is valid, but the javascript console asociated to the webview shows:
``` javascript
SyntaxError: JSON Parse error: Expected '}'
```
This JSON is not the expected JSON, the expected JSON has to be an array of object so:
```json
{ "response": "[ {\"value\": \"Portrait_Up\"}, {\"value\": \"Portrait_Down\"}, {\"value\": \"Landscape_Left\"}, {\"value\": \"Landscape_Right\}" ]", "statusCode": 200, "statusMessage": "OK" }
```
- __Remove the brackets {} of the response object. Has to be an array not an object__
- __Encapsulate every bean with brackets {}. It's an array of objects__

**Comment by fnva** [comment]
Please, check all the return array methods. The object on the response has to be an array
__Remove the brackets {} of the response object. Has to be an array not an object__

**Comment by fnva** [comment]
Another error referred to this is:
The output JSON from the native code is: 
```json
{ "response": "[ {\"value\": \"Portrait_Up\"}, {\"value\": \"Portrait_Down\"}, {\"value\": \"Landscape_Left\"}, {\"value\": \"Landscape_Right\"} ]", "statusCode": 200, "statusMessage": "OK" }
```
But the Typescript parsed object is: 
![screen shot 2015-01-30 at 12 19 24](https://cloud.githubusercontent.com/assets/8384895/5974918/0e5b8026-a87a-11e4-8d19-a91ae3aec1a7.png)

__Maybe this is related with the encapsulation of the elements inside the array__

**Comment by carloslozano** [comment]
So, even when the JSON response is valid... the parsing of the array is incorrect in javascript? :hankey:

**Comment by fnva** [comment]
Correct

**Comment by carloslozano** [comment]
This is APIResponse
```json
{ "response": "[ {\"value\": \"Portrait_Up\"}, {\"value\": \"Portrait_Down\"}, {\"value\": \"Landscape_Left\"}, {\"value\": \"Landscape_Right\"} ]", "statusCode": 200, "statusMessage": "OK" }
```

From TS/JS we retrieve the response:
```json
[ {"value": "Portrait_Up"}, {"value": "Portrait_Down"}, {"value": "Landscape_Left"}, {"value": "Landscape_Right"} ]
```
JSON parse is valid. :+1: 

But then we have an error parsing arrays...

```javascript
for(var __value__ in JSON.parse(apiResponse.getResponse())) {
   response.push(ICapabilitiesOrientation.toObject(__value__))
}
```

Where value is really an index and not an element! I'll fix this straight-away.

**Comment by carloslozano** [comment]
Fixed in commit https://github.com/AdaptiveMe/adaptive-arp-javascript/commit/d0193db10de4b0ec8e748bc592bc847ab0fe5050

**Comment by fnva** [comment]
Solved.
![screen shot 2015-01-30 at 12 58 42](https://cloud.githubusercontent.com/assets/8384895/5975322/8d8031c6-a87f-11e4-8434-e0289b5340db.png)
