### ISSUE TITLE
[ERROR] Service Implementation. Several issues

### ISSUE THREAD

**Issue by fnva** [AdaptiveMe/adaptive-arp-darwin#93]
__First issue__: Id is passed as String.
Change in every call of callback:
```javascript
\"\(getId())\"
```

for
```javascript
\(getId())
```
__Second issue__: Discuss the approach for non-escaping when the content of the response is a valid JSON:
```javascript
\(JSONUtil.escapeString(ServiceResponse.Serializer.toJSON(response)))
```

**Comment by carloslozano** [comment]
Escape the escape :smile:
